lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800 # 1 week
        token_extractors:
            authorization_header:
                enabled: true
                prefix: Bearer
                name: Authorization

when@prod:
    lexik_jwt_authentication:
        token_ttl: 900 # 15 minutes